#!/bin/bash
echo -ne "py3.3 classic_levenshtein\t\t"
python3.3 -m timeit -s "from pylev import Levenshtein" "Levenshtein.classic('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 recursive_levenshtein\t\t"
python3.3 -m timeit -s "from pylev import Levenshtein" "Levenshtein.recursive('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 wf_levenshtein\t\t\t"
python3.3 -m timeit -s "from pylev import Levenshtein" "Levenshtein.wf('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 wfi_levenshtein\t\t\t"
python3.3 -m timeit -s "from pylev import Levenshtein" "Levenshtein.wfi('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 damerau_levenshtein\t\t"
python3.3 -m timeit -s "from pylev import Levenshtein" "Levenshtein.damerau('Levenshtein', 'Frankenstein')"
