#!/bin/bash
echo -ne "py3.3 classic_levenshtein\t\t"
python3 -m timeit -n 1 -s "from pylev3 import Levenshtein" "Levenshtein.classic('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 recursive_levenshtein\t\t"
python3 -m timeit -n 1000 -s "from pylev3 import Levenshtein" "Levenshtein.recursive('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 wf_levenshtein\t\t\t"
python3 -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.wf('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 wfi_levenshtein\t\t\t"
python3 -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.wfi('Levenshtein', 'Frankenstein')"
echo -ne "py3.3 damerau_levenshtein\t\t"
python3 -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.damerau('Levenshtein', 'Frankenstein')"

echo -ne "pypy3 classic_levenshtein\t\t"
pypy -m timeit -n 1 -s "from pylev3 import Levenshtein" "Levenshtein.classic('Levenshtein', 'Frankenstein')"
echo -ne "pypy3 recursive_levenshtein\t\t"
pypy -m timeit -n 1000 -s "from pylev3 import Levenshtein" "Levenshtein.recursive('Levenshtein', 'Frankenstein')"
echo -ne "pypy3 wf_levenshtein\t\t\t"
pypy -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.wf('Levenshtein', 'Frankenstein')"
echo -ne "pypy3 wfi_levenshtein\t\t\t"
pypy -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.wfi('Levenshtein', 'Frankenstein')"
echo -ne "pypy3 damerau_levenshtein\t\t"
pypy -m timeit -s "from pylev3 import Levenshtein" "Levenshtein.damerau('Levenshtein', 'Frankenstein')"
